# Generated by Django 3.0.3 on 2020-02-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0024_borrowmoneyin_lendmoneyin_paymoneyin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowmoneyin',
            name='datetime',
            field=models.DateField(default='2020-02-06', verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='lendmoneyin',
            name='datetime',
            field=models.DateField(default='2020-02-06', verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='moneyin',
            name='datetime',
            field=models.DateField(default='2020-02-06', verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='paymoneyin',
            name='datetime',
            field=models.DateField(default='2020-02-06', verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth',
            field=models.DateField(blank=True, default='2020-02-06', null=True, verbose_name='出生日期'),
        ),
    ]
