# Generated by Django 3.0.3 on 2020-02-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0025_auto_20200206_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneyin',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='moneyin',
            name='article',
        ),
        migrations.RemoveField(
            model_name='moneyin',
            name='creatUser',
        ),
        migrations.RemoveField(
            model_name='moneyin',
            name='datetime',
        ),
        migrations.AddField(
            model_name='moneyin',
            name='tizhong',
            field=models.CharField(max_length=100, null=True, verbose_name='体重'),
        ),
        migrations.AddField(
            model_name='moneyin',
            name='xuechanggui',
            field=models.CharField(max_length=100, null=True, verbose_name='血常规'),
        ),
        migrations.AddField(
            model_name='moneyin',
            name='xueya',
            field=models.CharField(max_length=111, null=True, verbose_name='血压'),
        ),
    ]
