# Generated by Django 3.0.3 on 2020-02-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0026_auto_20200206_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='mhealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=100, null=True, verbose_name='体重')),
                ('blood_pressure', models.CharField(max_length=111, null=True, verbose_name='血压')),
                ('routine_blood_test', models.CharField(max_length=100, null=True, verbose_name='血常规')),
            ],
        ),
        migrations.DeleteModel(
            name='moneyin',
        ),
    ]
