# Generated by Django 3.0.3 on 2020-02-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0028_auto_20200207_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowmoneyin',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='所属人'),
        ),
    ]
